### ISSUE TITLE
Unable to build on Ubuntu 64-bit

### ISSUE THREAD

**Issue by sigmabeta** [lucashpandolfo/audacious-usf-plugin#1]
Configure script appears to output no error, but ends with the following:

```
checking if your platform is supported for the USF plugin... yes, AMD64 Linux
configure: touching .deps files
configure: creating ./config.status
config.status: creating buildsys.mk
config.status: creating extra.mk
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing po-directories commands
```

Afterwards, make outputs nothing but:

```
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by lucashpandolfo** [comment]
Try again with the latest version.
Also, there was an API change after audacious 3.4 (not sure about the exact version), so it may not even compile.
I have a wip for 3.6 but still needs some work.

**Comment by sigmabeta** [comment]
It does at least attempt to compile now, but it does fail as you mentioned. You could probably close this issue.

**Comment by lucashpandolfo** [comment]
¿Could you try now with the latest version?
I have successfully compiled it (an using it right now). Should signal several warnings during compilation but seems to work fine so far.

Remember you may need the audacious-devel package installed.

**Comment by sigmabeta** [comment]
Still fails, see attached pastebin:

http://hastebin.com/isumihejip.sm

I should have all the relevant libraries:

![image](https://cloud.githubusercontent.com/assets/1912034/7286245/859c5faa-e918-11e4-98e0-246a9c8389de.png)

**Comment by lucashpandolfo** [comment]
I see the problem. I started working in the plugin at version (i think) 3.3. It worked fine in 3.4.
Then, Audacious 3.5 had an api change and later 3.6 had another radical change.
You have 3.5, but I made the jump directly to 3.6 API.

**Comment by sigmabeta** [comment]
I figured it might be something like that. Don't worry too much about backward compatibility for my sake, I'm sure Ubuntu will move to Audacious 3.6 soon enough.

**Comment by sigmabeta** [comment]
Any chance you could post a binary of the 3.6 compatible version?

**Comment by lucashpandolfo** [comment]
I added the 3.6 64 bits binary. Keep in mind it may or may not work for you. (And it willl definetly not work in 3.5)

``` bash
└─(09:58:23 on master)──> ldd usf.so
        linux-vdso.so.1 (0x00007ffff7ffd000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffff7ad7000)
        libaudcore.so.3 => /usr/lib64/libaudcore.so.3 (0x00007ffff7894000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007ffff7590000)
        libz.so.1 => /lib64/libz.so.1 (0x00007ffff737a000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ffff7077000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007ffff6d6e000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ffff6b57000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffff67a9000)
        /lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
        libgmodule-2.0.so.0 => /usr/lib64/libgmodule-2.0.so.0 (0x00007ffff65a4000)
        libguess.so.1 => /usr/lib64/libguess.so.1 (0x00007ffff639c000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007ffff6136000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ffff5f31000)
        libmowgli.so.2 => /usr/lib64/libmowgli.so.2 (0x00007ffff5d1f000)
```

**Comment by sigmabeta** [comment]
I ended up being able to build the 3.6 64-bit binary as well. Thanks for the fix.

**Comment by yisraeldov** [comment]
Hi I'm just trying to complie now and not working for me 

```
plugin.cc:19:50: error: cannot declare variable ‘aud_plugin_instance’ to be of abstract type ‘USFPlugin’
 __attribute__((visibility("default"))) USFPlugin aud_plugin_instance;
```
